### ISSUE TITLE
New link into the article section

### ISSUE THREAD

**Issue by TheBojda** [semaphore-protocol/website#106]
Hi! I have an article about ZKP. Can I add it to the article section of the documentation?

I think it could help a lot of beginners to understand ZKP and how semaphore works. 

Semaphore is super cool, but complex for a beginner. In my article, I show how the basics work through the source code of Tornado Cash (they are using the same method as semaphore but in a simpler way)

My article: https://medium.com/@thebojda/how-i-built-an-anonymous-voting-system-on-the-ethereum-blockchain-using-zero-knowledge-proof-d5ab286228fd

Thx

**Comment by cedoor** [comment]
Hi @TheBojda, thanks for the article! For the time being, it would be preferable to keep only articles strictly related to Semaphore though.
