### ISSUE TITLE
Include `pnpm` as a package manager in the docs

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/website#109]
In the documentation, there are two ways now displayed to install dependencies: `npm` and `yarn`. It would be nice to add `pnpm` too.

**Example:**
How it looks:
https://semaphore.pse.dev/docs/guides/identities#install-library
The code of that:
https://github.com/semaphore-protocol/website/blob/main/versioned_docs/version-V3/guides/identities.mdx#L29-L50

The idea would be to add a new label, something like: `{label: 'pnpm', value: 'pnpm'},` and a new `TabItem` like:
````ts
<TabItem value="pnpm">

```bash
pnpm add @semaphore-protocol/identity
```
</TabItem>
````

In all the places that this code blocks appear to install dependencies.

**More info :**
https://docusaurus.io/docs/markdown-features/tabs#customizing-tab-headings

**Comment by sumitvekariya** [comment]
Hey, I would like help on this, can you please add the description?

Thanks

**Comment by vplasencia** [comment]
Hey @sumitvekariya thank you, sure, I just added the description. Please, let us know if you need more information.

**Comment by sumitvekariya** [comment]
Here is the PR: https://github.com/semaphore-protocol/website/pull/110  @vplasencia
