### ISSUE TITLE
New glossary term: Zero value

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/website#21]
**Why do you think it is important?**

People may be confused as it is not clear what it is used for and how to choose the right value. Groups are an abstraction of Merkle trees, but it is still necessary to explain how a Merkle tree works for those who want to go deeper.

**Comment by DezyIC** [comment]
Zero value: variables declared without an explicit initial value are termed 'zero value'.

The zero value is:

0 - for numeric types,
false - for the boolean type, and
" " - (the empty string) for strings.

**Comment by Jo-Shino** [comment]
@cedoor 
Hello. 
DezyIC already wrote a sample explanation of Zero value above though, may I add it to the glossary on the website?

**Comment by cedoor** [comment]
Hi @Jo-Shino, that definition doesn't reflect what a zero value is in Semaphore actually. It can even be a number different from 0.  Also, that parameter is now defined automatically, so it may not be necessary anymore to have a definition in our glossary 🤔 

@vplasencia

**Comment by Jo-Shino** [comment]
Oh I see, then I'd like to tackle this #46 issue instead of this issue. Is it possible?

**Comment by vplasencia** [comment]
Hey @Jo-Shino! Sure, go for #46 👍

**Comment by Jo-Shino** [comment]
thank you!
