### ISSUE TITLE
Add Twitter in footer

### ISSUE THREAD

**Issue by epicfox87** [semaphore-protocol/website#36]
In the footer 'Connect' section, add Twitter & link to https://twitter.com/PrivacyScaling.

Another small fix in footer, change "Copyright © 2022 Ethereum Foundation" to "Copyright © 2023 Ethereum Foundation"

**Comment by cedoor** [comment]
Hey @epicfox87, thanks! The copyright year has been updated. There's already a link to the PSE website on the left, where people can find PSE references.
