### ISSUE TITLE
New glossary term: Signals

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/website#46]
**Why do you think it is important?**

A Semaphore signal is a value that people with a Semaphore identity belonging to a group can broadcast anonymously. In the case of an anonymous voting system, the signal may, for example, be the vote. On [Circom](https://docs.circom.io/circom-language/signals/), however, the signals are more generically all those values that contain a field element in Z/pZ.

Signal is a term used widely in many different environments, and that is why a more precise definition of "Semaphore signals" on the documentation would be needed.

**Comment by vplasencia** [comment]
Something about the definition of signal by Barry Whitehat (with text and video at the specific time).

**Text:**

> **This signal is just like 32 bytes and it is the hash of something that you want to say. I mean, it could be the hash of a tweet, or it could be the hash of a vote or it could be the hash of something else.**

**Video:**

https://youtu.be/lv6iK9qezBY?t=952

**Comment by Jo-Shino** [comment]
As I mentioned above the issue #21, I'll tackle this issue in this week!
